=head1 REPOSITORY

L<https://github.com/dkogan/mrgingham>

=head1 AUTHOR

Dima Kogan, C<< <dima@secretsauce.net> >>

=head1 LICENSE AND COPYRIGHT

This library is free software; you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License as published by the Free
Software Foundation; either version 2.1 of the License, or (at your option) any
later version.

Copyright 2017-2018 California Institute of Technology

Copyright 2017-2018 Dima Kogan (C<dima@secretsauce.net>)
